name: Harden runnerv2

on: [push, issues, workflow_dispatch]

jobs:
  greeting:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # rc
      with:
        policy: policy1

    - uses: actions/first-interaction@1d8459ca65b335265f1285568221e229d45a995e # v1.1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"

    - run: curl -X GET https://auth.docker.io
    - run: sleep 40
    - run: curl -X GET https://auth.docker.io
    - run: sleep 40
    - run: curl -X GET https://auth.docker.io
    - run: sleep 40
    - run: curl -X GET https://google.com
