# .github/workflows/pull_request.yml
name: Deploy to trigger workflows

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-?*"
  workflow_run:
    workflows:
      - "CD"
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v3.6.0
        
      - name: Run tests
        run: echo "Running tests on pull request..."
        
      
