# .github/workflows/pull_request.yml
name: Deploy to trigger workflows

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-?*"
  workflow_run:
    workflows:
      - "CD"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run tests
        run: echo "Running tests on pull request..."
        
      
