name: CD

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@arc
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@09cecabe1f169596b81c2ef22b40faff87acc460 # v0.9.0"
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: docker build . -t gcr.io/$GCLOUD_PROJECT/accessmanagerv3:$GITHUB_SHA

      - name: Push Docker image
        run: docker push gcr.io/$GCLOUD_PROJECT/accessmanagerv3:$GITHUB_SHA
