name: reviewdog
on: [pull_request]
jobs:
  linter_name:
    name: runner
    runs-on: ubuntu-latest
    steps:
      - name: hr
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: reviewdog/action-languagetool@25e378de3d0d54cd398136c238d9da2831391681 # v1.19.0
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Change reporter level if you need.
          level: info
