name: reviewdog
on: [pull_request]
permissions:
  contents: read

jobs:
  misspell:
    permissions:
      checks: write  # for reviewdog/action-misspell to report issues using checks
      contents: read  # for actions/checkout to fetch code
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: hr
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit
      - name: Check out code.
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: misspell
        uses: reviewdog/action-misspell@5bd7be2fc7ae56a517184f5c4bbcf2fd7afe3927 # v1.17.0
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
