name: reviewdog
on: [pull_request]
permissions:
  contents: read

jobs:
  misspell:
    permissions:
      checks: write  # for reviewdog/action-misspell to report issues using checks
      contents: read  # for actions/checkout to fetch code
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: hr
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Check out code.
        uses: actions/checkout@v4
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
