name: reviewdog
on: [pull_request]
permissions:
  contents: read

jobs:
  misspell:
    permissions:
      checks: write  # for reviewdog/action-misspell to report issues using checks
      contents: read  # for actions/checkout to fetch code
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: hr
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - name: Check out code.
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: misspell
        uses: reviewdog/action-misspell@06d6a480724fa783c220081bbc22336a78dbbe82 # v1.15.0
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
