# .github/workflows/on_workflow_completion.yml
name: Run on Pull Request Workflow Completion

on:
  workflow_run:
    workflows: ["Deploy to trigger workflows"]
    types:
      - completed

jobs:
  run_after_completion:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && !github.event.workflow_run.head_repository.fork }}
    #if: ${{ github.event.workflow_run.conclusion == 'success' && !github.event.workflow_run.head_repository.fork && (github.event.workflow_run.event == 'push' || github.event.workflow_run.event == 'workflow_run') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          token: ${{ secrets.PAT1 }}
        
      - name: Post-workflow step
        run: echo "This runs after the pull request workflow completes successfully."

      - name: Tag Code and push
        run: |
          git config --global user.email "test@test.com"
          git config --global user.name "test"
          git tag --force v1 --message "Tagging commit"
          git push --set-upstream origin --tags

      
      - run: |
          TAG=v1
          echo "Checking if tag ${TAG} exists..."
      
          # Check if the tag exists
          if [ $(git tag -l "${TAG}") ]; then
            echo "Tag ${TAG} exists. Proceeding..."
      
            # Log tag existence to GitHub Actions output
            echo "tag_exists=true" >> $GITHUB_OUTPUT
      
            # Get the commit associated with the tag
            COMMIT=$(git rev-list -n 1 ${TAG})
            echo "Commit for tag ${TAG} is ${COMMIT}"
      
            # Check if the commit is in the 'main' branch
            if git branch --contains ${COMMIT} | grep -q main; then
              echo "Commit ${COMMIT} is found in the 'main' branch."
      
              # Log the commit to GitHub Actions output
              echo "tag_commit=${COMMIT}" >> $GITHUB_OUTPUT
            else
              echo "ERROR: Commit ${COMMIT} is NOT in the 'main' branch!"
              
            fi
          else
            # Log failure if the tag doesn't exist
            echo "ERROR: Tag ${TAG} does not exist. Cancelling the run."
            gh run cancel ${{ github.run_id }}
          fi

      
      - name: Print github.event.workflow_run properties
        run: |
          echo "Printing github.event.workflow_run properties:"
          echo "${{ toJson(github.event.workflow_run) }}"
