# .github/workflows/on_workflow_completion.yml
name: Run on Pull Request Workflow Completion

on:
  workflow_run:
    workflows: ["Deploy to trigger workflows"]
    types:
      - completed

jobs:
  run_after_completion:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && !github.event.workflow_run.head_repository.fork }}
    #if: ${{ github.event.workflow_run.conclusion == 'success' && !github.event.workflow_run.head_repository.fork && (github.event.workflow_run.event == 'push' || github.event.workflow_run.event == 'workflow_run') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          token: ${{ secrets.PAT1 }}
        
      - name: Post-workflow step
        run: echo "This runs after the pull request workflow completes successfully."

      - name: Tag Code and push
        run: |
          git config --global user.email "test@test.com"
          git config --global user.name "test"
          git tag --force v1 --message "Tagging commit"
          git push --set-upstream origin --tags

      
      - run: |
          TAG=v1
          if [ $(git tag -l "v1") ]; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
            COMMIT=`git rev-list -n 1 v1`
            git branch --contains ${COMMIT} | grep -q main
            echo "xts_tag_commit=`${COMMIT}`" >> $GITHUB_OUTPUT
             
          else
            gh run cancel ${{ github.run_id }}
          fi
      
      - name: Print github.event.workflow_run properties
        run: |
          echo "Printing github.event.workflow_run properties:"
          echo "${{ toJson(github.event.workflow_run) }}"
