name: Reusable workflow example

on:
  workflow_call:
    
permissions:
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js 15.x
      uses: actions/setup-node@v1
      with:
       node-version: 15.x
